export const START_ESCORT_REQUEST = 'Home/Escort/RequestEscortScreen/START_ESCORT_REQUEST';
export const START_ESCORT_FAILURE = 'Home/Escort/RequestEscortScreen/START_ESCORT_FAILURE';
export const START_ESCORT_SUCCESS = 'Home/Escort/RequestEscortScreen/START_ESCORT_SUCCESS';
export const CANCEL_ESCORT_REQUEST = 'Home/Escort/RequestEscortScreen/CANCEL_ESCORT_REQUEST';
export const CANCEL_ESCORT_FAILURE = 'Home/Escort/RequestEscortScreen/CANCEL_ESCORT_FAILURE';
export const CANCEL_ESCORT_SUCCESS = 'Home/Escort/RequestEscortScreen/CANCEL_ESCORT_SUCCESS';
export const SHOW_CANCEL_ESCORT_MODAL = 'Home/Escort/RequestEscortScreen/SHOW_CANCEL_ESCORT_MODAL';
export const HIDE_CANCEL_ESCORT_MODAL = 'Home/Escort/RequestEscortScreen/HIDE_CANCEL_ESCORT_MODAL';
export const ADD_PENDING_ESCORT = 'Home/Escort/RequestEscortScreen/ADD_PENDING_ESCORT';
//# sourceMappingURL=constants.js.map