"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_USER_NOTIFICATION_SUCCESS = exports.TOGGLE_USER_NOTIFICATION_REQUEST = exports.TOGGLE_USER_NOTIFICATION_FAILURE = exports.RESET_DELETE_USER = exports.DELETE_USER_SUCCESS = exports.DELETE_USER_REQUEST = exports.DELETE_USER_FAILURE = void 0;
/**
 *
 * NotificationScreen constants
 *
 */

const TOGGLE_USER_NOTIFICATION_REQUEST = exports.TOGGLE_USER_NOTIFICATION_REQUEST = 'Menu/NotificationScreen/TOGGLE_USER_NOTIFICATION_REQUEST';
const TOGGLE_USER_NOTIFICATION_FAILURE = exports.TOGGLE_USER_NOTIFICATION_FAILURE = 'Menu/NotificationScreen/TOGGLE_USER_NOTIFICATION_FAILURE';
const TOGGLE_USER_NOTIFICATION_SUCCESS = exports.TOGGLE_USER_NOTIFICATION_SUCCESS = 'Menu/NotificationScreen/TOGGLE_USER_NOTIFICATION_SUCCESS';
const DELETE_USER_REQUEST = exports.DELETE_USER_REQUEST = 'Menu/NotificationScreen/DELETE_USER_REQUEST';
const DELETE_USER_FAILURE = exports.DELETE_USER_FAILURE = 'Menu/NotificationScreen/DELETE_USER_FAILURE';
const DELETE_USER_SUCCESS = exports.DELETE_USER_SUCCESS = 'Menu/NotificationScreen/DELETE_USER_SUCCESS';
const RESET_DELETE_USER = exports.RESET_DELETE_USER = 'Menu/NotificationScreen/RESET_DELETE_USER';
//# sourceMappingURL=constants.js.map