/**
 *
 * OrganizationScreen constants
 *
 */

export const GET_USER_ORGANIZATIONS_REQUEST =
  'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_REQUEST';
export const GET_USER_ORGANIZATIONS_FAILURE =
  'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_FAILURE';
export const GET_USER_ORGANIZATIONS_SUCCESS =
  'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_SUCCESS';
export const DELETE_USER_ORGANIZATION_REQUEST =
  'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_REQUEST';
export const DELETE_USER_ORGANIZATION_FAILURE =
  'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_FAILURE';
export const DELETE_USER_ORGANIZATION_SUCCESS =
  'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_SUCCESS';
