"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPLOAD_VIDEO_SUCCESS = exports.UPLOAD_VIDEO_REQUEST = exports.UPLOAD_VIDEO_FAILURE = exports.SHOW_CHAT_MODAL = exports.SHOW_CALL_MODAL = exports.SEND_MESSAGE_SUCCESS = exports.SEND_MESSAGE_REQUEST = exports.SEND_MESSAGE_FAILURE = exports.HIDE_CHAT_MODAL = exports.HIDE_CALL_MODAL = exports.GET_MESSAGES_SUCCESS = exports.GET_MESSAGES_REQUEST = exports.GET_MESSAGES_FAILURE = exports.GET_INCIDENT_VIDEOS_SUCCESS = exports.GET_INCIDENT_VIDEOS_REQUEST = exports.GET_INCIDENT_VIDEOS_FAILURE = exports.GET_INCIDENT_SUCCESS = exports.GET_INCIDENT_REQUEST = exports.GET_INCIDENT_FAILURE = exports.ADD_MESSAGE = exports.ADD_INCIDENT_VIDEO = void 0;
/**
 *
 * TipDetailScreen constants
 *
 */

const GET_INCIDENT_REQUEST = exports.GET_INCIDENT_REQUEST = 'Home/Tips/TipDetailScreen/GET_INCIDENT_REQUEST';
const GET_INCIDENT_FAILURE = exports.GET_INCIDENT_FAILURE = 'Home/Tips/TipDetailScreen/GET_INCIDENT_FAILURE';
const GET_INCIDENT_SUCCESS = exports.GET_INCIDENT_SUCCESS = 'Home/Tips/TipDetailScreen/GET_INCIDENT_SUCCESS';
const GET_INCIDENT_VIDEOS_REQUEST = exports.GET_INCIDENT_VIDEOS_REQUEST = 'Home/Tips/TipDetailScreen/GET_INCIDENT_VIDEOS_REQUEST';
const GET_INCIDENT_VIDEOS_FAILURE = exports.GET_INCIDENT_VIDEOS_FAILURE = 'Home/Tips/TipDetailScreen/GET_INCIDENT_VIDEOS_FAILURE';
const GET_INCIDENT_VIDEOS_SUCCESS = exports.GET_INCIDENT_VIDEOS_SUCCESS = 'Home/Tips/TipDetailScreen/GET_INCIDENT_VIDEOS_SUCCESS';
const SHOW_CALL_MODAL = exports.SHOW_CALL_MODAL = 'Home/Tips/TipDetailScreen/SHOW_CALL_MODAL';
const HIDE_CALL_MODAL = exports.HIDE_CALL_MODAL = 'Home/Tips/TipDetailScreen/HIDE_CALL_MODAL';
const SHOW_CHAT_MODAL = exports.SHOW_CHAT_MODAL = 'Home/Tips/TipDetailScreen/SHOW_CHAT_MODAL';
const HIDE_CHAT_MODAL = exports.HIDE_CHAT_MODAL = 'Home/Tips/TipDetailScreen/HIDE_CHAT_MODAL';
const UPLOAD_VIDEO_REQUEST = exports.UPLOAD_VIDEO_REQUEST = 'Home/Tips/TipDetailScreen/UPLOAD_VIDEO_REQUEST';
const UPLOAD_VIDEO_FAILURE = exports.UPLOAD_VIDEO_FAILURE = 'Home/Tips/TipDetailScreen/UPLOAD_VIDEO_FAILURE';
const UPLOAD_VIDEO_SUCCESS = exports.UPLOAD_VIDEO_SUCCESS = 'Home/Tips/TipDetailScreen/UPLOAD_VIDEO_SUCCESS';
const ADD_INCIDENT_VIDEO = exports.ADD_INCIDENT_VIDEO = 'Home/Tips/TipDetailScreen/ADD_INCIDENT_VIDEO';
const GET_MESSAGES_REQUEST = exports.GET_MESSAGES_REQUEST = 'Home/Tips/TipDetailScreen/GET_MESSAGES_REQUEST';
const GET_MESSAGES_FAILURE = exports.GET_MESSAGES_FAILURE = 'Home/Tips/TipDetailScreen/GET_MESSAGES_FAILURE';
const GET_MESSAGES_SUCCESS = exports.GET_MESSAGES_SUCCESS = 'Home/Tips/TipDetailScreen/GET_MESSAGES_SUCCESS';
const ADD_MESSAGE = exports.ADD_MESSAGE = 'Home/Tips/TipDetailScreen/ADD_MESSAGE';
const SEND_MESSAGE_REQUEST = exports.SEND_MESSAGE_REQUEST = 'Home/Tips/TipDetailScreen/SEND_MESSAGE_REQUEST';
const SEND_MESSAGE_FAILURE = exports.SEND_MESSAGE_FAILURE = 'Home/Tips/TipDetailScreen/SEND_MESSAGE_FAILURE';
const SEND_MESSAGE_SUCCESS = exports.SEND_MESSAGE_SUCCESS = 'Home/Tips/TipDetailScreen/SEND_MESSAGE_SUCCESS';
//# sourceMappingURL=constants.js.map