"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_READUNREAD_STATUS_SUCCESS = exports.UPDATE_READUNREAD_STATUS_REQUEST = exports.UPDATE_READUNREAD_STATUS_FAILURE = exports.RESET_UPDATE_READUNREAD_STATUS = exports.READ_ALL_NOTIFICATION_SUCCESS = exports.READ_ALL_NOTIFICATION_REQUEST = exports.READ_ALL_NOTIFICATION_FAILURE = exports.NOTIFICATION_UNREAD_COUNT = exports.NOTIFICATION_LIST_SUCCESS = exports.NOTIFICATION_LIST_RESET = exports.NOTIFICATION_LIST_REQUEST = exports.NOTIFICATION_LIST_FAILURE = void 0;
/**
 *
 * Notification List Screen constants
 *
 */

const NOTIFICATION_LIST_REQUEST = exports.NOTIFICATION_LIST_REQUEST = 'Menu/NotificationListScreen/NOTIFICATION_LIST_REQUEST';
const NOTIFICATION_LIST_FAILURE = exports.NOTIFICATION_LIST_FAILURE = 'Menu/NotificationListScreen/NOTIFICATION_LIST_FAILURE';
const NOTIFICATION_LIST_SUCCESS = exports.NOTIFICATION_LIST_SUCCESS = 'Menu/NotificationListScreen/NOTIFICATION_LIST_SUCCESS';
const NOTIFICATION_LIST_RESET = exports.NOTIFICATION_LIST_RESET = 'Menu/NotificationListScreen/NOTIFICATION_LIST_RESET';
const NOTIFICATION_UNREAD_COUNT = exports.NOTIFICATION_UNREAD_COUNT = 'Menu/NotificationListScreen/NOTIFICATION_UNREAD_COUNT';
const UPDATE_READUNREAD_STATUS_REQUEST = exports.UPDATE_READUNREAD_STATUS_REQUEST = 'Menu/NotificationListScreen/UPDATE_READUNREAD_STATUS_REQUEST';
const UPDATE_READUNREAD_STATUS_FAILURE = exports.UPDATE_READUNREAD_STATUS_FAILURE = 'Menu/NotificationListScreen/UPDATE_READUNREAD_STATUS_FAILURE';
const UPDATE_READUNREAD_STATUS_SUCCESS = exports.UPDATE_READUNREAD_STATUS_SUCCESS = 'Menu/NotificationListScreen/UPDATE_READUNREAD_STATUS_SUCCESS';
const RESET_UPDATE_READUNREAD_STATUS = exports.RESET_UPDATE_READUNREAD_STATUS = 'Menu/NotificationListScreen/RESET_UPDATE_READUNREAD_STATUS';
const READ_ALL_NOTIFICATION_REQUEST = exports.READ_ALL_NOTIFICATION_REQUEST = 'Menu/NotificationListScreen/READ_ALL_NOTIFICATION_REQUEST';
const READ_ALL_NOTIFICATION_SUCCESS = exports.READ_ALL_NOTIFICATION_SUCCESS = 'Menu/NotificationListScreen/READ_ALL_NOTIFICATION_SUCCESS';
const READ_ALL_NOTIFICATION_FAILURE = exports.READ_ALL_NOTIFICATION_FAILURE = 'Menu/NotificationListScreen/READ_ALL_NOTIFICATION_FAILURE';
//# sourceMappingURL=constants.js.map