#!/bin/zsh
# install-all.sh

yarn add \
@formatjs/intl-datetimeformat@^6.4.3 \
@formatjs/intl-getcanonicallocales@^2.0.5 \
@formatjs/intl-locale@^3.0.11 \
@formatjs/intl-numberformat@^8.3.3 \
@formatjs/intl-pluralrules@^5.1.8 \
@react-native-async-storage/async-storage@^1.17.11 \
@react-native-community/art@1.0.3 \
@react-native-community/cli-platform-android@^10.1.3 \
@react-native-community/netinfo@5.9.9 \
@react-native-community/push-notification-ios@1.10.1 \
@react-native-firebase/analytics@11.0.0 \
@react-native-firebase/app@11.0.0 \
@react-native-firebase/crashlytics@11.0.0 \
@react-native-firebase/messaging@11.0.0 \
@react-navigation/native@^6.1.1 \
@react-navigation/native-stack@^6.9.7 \
@reduxjs/toolkit@^1.9.1 \
@twilio/conversations@2.1.0 \
@types/react-native-push-notification@8.1.1 \
date-fns@^4.1.0 \
events@^3.3.0 \
install@^0.13.0 \
intl@^1.2.5 \
merge@^2.1.1 \
microdiff@^1.5.0 \
npm@^9.2.0 \
react-intl@^6.2.5 \
react-native-android-location-services-dialog-box@2.8.2 \
react-native-background-actions@2.6.6 \
react-native-background-fetch@4.0.3 \
react-native-background-geolocation@4.18.3 \
react-native-background-timer@2.4.1 \
react-native-battery-optimization-check@1.0.8 \
react-native-camera@3.15.0 \
react-native-contacts@5.0.6 \
react-native-device-info@^10.3.0 \
react-native-fs@2.16.6 \
react-native-geolocation-service@5.3.1 \
react-native-gesture-handler@1.5.2 \
react-native-image-picker@4.0.6 \
react-native-image-resizer@1.4.5 \
react-native-in-app-message@1.0.31 \
react-native-keep-awake@4.0.0 \
react-native-linear-gradient@2.5.6 \
react-native-localize@2.2.4 \
react-native-maps@0.26.1 \
react-native-permissions@3.8.0 \
react-native-push-notification@8.1.1 \
react-native-reanimated@1.4.0 \
react-native-root-toast@3.2.1 \
react-native-safe-area-context@3.2.0 \
react-native-screens@3.18.0 \
react-native-svg@13.7.0 \
react-native-twilio-video-webrtc@https://github.com/blackuy/react-native-twilio-video-webrtc \
react-native-vector-icons@8.1.0 \
react-native-video@5.0.2 \
react-native-webview@11.14.1 \
react-navigation-tabs@2.7.0 \
reactotron-react-native@4.0.2 \
reactotron-redux@3.1.2 \
reactotron-redux-saga@4.2.3 \
redux@4.0.4 \
redux-devtools-extension@2.13.8 \
redux-form@^8.3.9 \
redux-persist@^6.0.0 \
redux-promise-listener@^1.1.1 \
redux-saga@1.1.3 \
rn-fetch-blob@0.12.0 \
url-join@^5.0.0