"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.GET_USER_ORGANIZATIONS_SUCCESS = exports.GET_USER_ORGANIZATIONS_REQUEST = exports.GET_USER_ORGANIZATIONS_FAILURE = exports.DELETE_USER_ORGANIZATION_SUCCESS = exports.DELETE_USER_ORGANIZATION_REQUEST = exports.DELETE_USER_ORGANIZATION_FAILURE = void 0;
/**
 *
 * OrganizationScreen constants
 *
 */

const GET_USER_ORGANIZATIONS_REQUEST = exports.GET_USER_ORGANIZATIONS_REQUEST = 'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_REQUEST';
const GET_USER_ORGANIZATIONS_FAILURE = exports.GET_USER_ORGANIZATIONS_FAILURE = 'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_FAILURE';
const GET_USER_ORGANIZATIONS_SUCCESS = exports.GET_USER_ORGANIZATIONS_SUCCESS = 'Menu/OrganizationScreen/GET_USER_ORGANIZATIONS_SUCCESS';
const DELETE_USER_ORGANIZATION_REQUEST = exports.DELETE_USER_ORGANIZATION_REQUEST = 'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_REQUEST';
const DELETE_USER_ORGANIZATION_FAILURE = exports.DELETE_USER_ORGANIZATION_FAILURE = 'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_FAILURE';
const DELETE_USER_ORGANIZATION_SUCCESS = exports.DELETE_USER_ORGANIZATION_SUCCESS = 'Menu/OrganizationScreen/DELETE_USER_ORGANIZATION_SUCCESS';
//# sourceMappingURL=constants.js.map