"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPLOAD_VIDEO_SUCCESS = exports.UPLOAD_VIDEO_REQUEST = exports.UPLOAD_VIDEO_FAILURE = exports.SHOW_TIP_CREATED_MODAL = exports.SHOW_FAST_ACCESS_MODAL = exports.SHOW_CANCEL_INCIDENT_MODAL = exports.SHOW_CALL_MODAL = exports.HIDE_TIP_CREATED_MODAL = exports.HIDE_FAST_ACCESS_MODAL = exports.HIDE_CANCEL_INCIDENT_MODAL = exports.HIDE_CALL_MODAL = exports.GET_USER_ORGANIZATIONS_SUCCESS = exports.GET_USER_ORGANIZATIONS_REQUEST = exports.GET_USER_ORGANIZATIONS_FAILURE = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_SUCCESS = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_REQUEST = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_FAILURE = exports.DELETE_INCIDENT_SUCCESS = exports.DELETE_INCIDENT_REQUEST = exports.DELETE_INCIDENT_FAILURE = exports.CREATE_TIP_WITH_CHAT_SUCCESS = exports.CREATE_TIP_WITH_CHAT_REQUEST = exports.CREATE_TIP_WITH_CHAT_FAILURE = exports.CREATE_INCIDENT_SUCCESS = exports.CREATE_INCIDENT_REQUEST = exports.CREATE_INCIDENT_FAILURE = exports.ADD_INCIDENT_VIDEO = void 0;
/**
 *
 * VideoRecordScreen constants
 *
 */

const UPLOAD_VIDEO_REQUEST = exports.UPLOAD_VIDEO_REQUEST = 'Home/NewTip/VideoRecordScreen/UPLOAD_VIDEO_REQUEST';
const UPLOAD_VIDEO_FAILURE = exports.UPLOAD_VIDEO_FAILURE = 'Home/NewTip/VideoRecordScreen/UPLOAD_VIDEO_FAILURE';
const UPLOAD_VIDEO_SUCCESS = exports.UPLOAD_VIDEO_SUCCESS = 'Home/NewTip/VideoRecordScreen/UPLOAD_VIDEO_SUCCESS';
const CREATE_INCIDENT_REQUEST = exports.CREATE_INCIDENT_REQUEST = 'Home/NewTip/VideoRecordScreen/CREATE_INCIDENT_REQUEST';
const CREATE_INCIDENT_FAILURE = exports.CREATE_INCIDENT_FAILURE = 'Home/NewTip/VideoRecordScreen/CREATE_INCIDENT_FAILURE';
const CREATE_INCIDENT_SUCCESS = exports.CREATE_INCIDENT_SUCCESS = 'Home/NewTip/VideoRecordScreen/CREATE_INCIDENT_SUCCESS';
const DELETE_INCIDENT_REQUEST = exports.DELETE_INCIDENT_REQUEST = 'Home/NewTip/VideoRecordScreen/DELETE_INCIDENT_REQUEST';
const DELETE_INCIDENT_FAILURE = exports.DELETE_INCIDENT_FAILURE = 'Home/NewTip/VideoRecordScreen/DELETE_INCIDENT_FAILURE';
const DELETE_INCIDENT_SUCCESS = exports.DELETE_INCIDENT_SUCCESS = 'Home/NewTip/VideoRecordScreen/DELETE_INCIDENT_SUCCESS';
const ADD_INCIDENT_VIDEO = exports.ADD_INCIDENT_VIDEO = 'Home/NewTip/VideoRecordScreen/ADD_INCIDENT_VIDEO';
const SHOW_CANCEL_INCIDENT_MODAL = exports.SHOW_CANCEL_INCIDENT_MODAL = 'Home/NewTip/VideoRecordScreen/SHOW_DELETE_INCIDENT_MODAL';
const HIDE_CANCEL_INCIDENT_MODAL = exports.HIDE_CANCEL_INCIDENT_MODAL = 'Home/NewTip/VideoRecordScreen/HIDE_DELETE_INCIDENT_MODAL';
const SHOW_CALL_MODAL = exports.SHOW_CALL_MODAL = 'Home/NewTip/VideoRecordScreen/SHOW_CALL_MODAL';
const HIDE_CALL_MODAL = exports.HIDE_CALL_MODAL = 'Home/NewTip/VideoRecordScreen/HIDE_CALL_MODAL';
const GET_USER_ORGANIZATIONS_REQUEST = exports.GET_USER_ORGANIZATIONS_REQUEST = 'Home/NewTip/VideoRecordScreen/GET_USER_ORGANIZATIONS_REQUEST';
const GET_USER_ORGANIZATIONS_FAILURE = exports.GET_USER_ORGANIZATIONS_FAILURE = 'Home/NewTip/VideoRecordScreen/GET_USER_ORGANIZATIONS_FAILURE';
const GET_USER_ORGANIZATIONS_SUCCESS = exports.GET_USER_ORGANIZATIONS_SUCCESS = 'Home/NewTip/VideoRecordScreen/GET_USER_ORGANIZATIONS_SUCCESS';
const CREATE_TIP_WITH_CHAT_REQUEST = exports.CREATE_TIP_WITH_CHAT_REQUEST = 'Home/NewTip/VideoRecordScreen/CREATE_TIP_WITH_CHAT_REQUEST';
const CREATE_TIP_WITH_CHAT_FAILURE = exports.CREATE_TIP_WITH_CHAT_FAILURE = 'Home/NewTip/VideoRecordScreen/CREATE_TIP_WITH_CHAT_FAILURE';
const CREATE_TIP_WITH_CHAT_SUCCESS = exports.CREATE_TIP_WITH_CHAT_SUCCESS = 'Home/NewTip/VideoRecordScreen/CREATE_TIP_WITH_CHAT_SUCCESS';
const SHOW_TIP_CREATED_MODAL = exports.SHOW_TIP_CREATED_MODAL = 'Home/NewTip/VideoRecordScreen/SHOW_TIP_CREATED_MODAL';
const HIDE_TIP_CREATED_MODAL = exports.HIDE_TIP_CREATED_MODAL = 'Home/NewTip/VideoRecordScreen/HIDE_TIP_CREATED_MODAL';
const SHOW_FAST_ACCESS_MODAL = exports.SHOW_FAST_ACCESS_MODAL = 'Home/NewTip/VideoRecordScreen/SHOW_FAST_ACCESS_MODAL';
const HIDE_FAST_ACCESS_MODAL = exports.HIDE_FAST_ACCESS_MODAL = 'Home/NewTip/VideoRecordScreen/HIDE_FAST_ACCESS_MODAL';
const GET_LAST_ACTIVE_TIP_ORGANIZATION_REQUEST = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_REQUEST = 'Home/NewTip/VideoRecordScreen/GET_LAST_ACTIVE_TIP_ORGANIZATION_REQUEST';
const GET_LAST_ACTIVE_TIP_ORGANIZATION_FAILURE = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_FAILURE = 'Home/NewTip/VideoRecordScreen/GET_LAST_ACTIVE_TIP_ORGANIZATION_FAILURE';
const GET_LAST_ACTIVE_TIP_ORGANIZATION_SUCCESS = exports.GET_LAST_ACTIVE_TIP_ORGANIZATION_SUCCESS = 'Home/NewTip/VideoRecordScreen/GET_LAST_ACTIVE_TIP_ORGANIZATION_SUCCESS';
//# sourceMappingURL=constants.js.map