"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_CONTACT_NOTIFICATION_SUCCESS = exports.TOGGLE_CONTACT_NOTIFICATION_REQUEST = exports.TOGGLE_CONTACT_NOTIFICATION_FAILURE = exports.DELETE_CONTACT_SUCCESS = exports.DELETE_CONTACT_REQUEST = exports.DELETE_CONTACT_FAILURE = void 0;
/**
 *
 * ContactScreen constants
 *
 */

const TOGGLE_CONTACT_NOTIFICATION_REQUEST = exports.TOGGLE_CONTACT_NOTIFICATION_REQUEST = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_REQUEST';
const TOGGLE_CONTACT_NOTIFICATION_FAILURE = exports.TOGGLE_CONTACT_NOTIFICATION_FAILURE = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_FAILURE';
const TOGGLE_CONTACT_NOTIFICATION_SUCCESS = exports.TOGGLE_CONTACT_NOTIFICATION_SUCCESS = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_SUCCESS';
const DELETE_CONTACT_REQUEST = exports.DELETE_CONTACT_REQUEST = 'Home/ContactScreen/DELETE_CONTACT_REQUEST';
const DELETE_CONTACT_FAILURE = exports.DELETE_CONTACT_FAILURE = 'Home/ContactScreen/DELETE_CONTACT_FAILURE';
const DELETE_CONTACT_SUCCESS = exports.DELETE_CONTACT_SUCCESS = 'Home/ContactScreen/DELETE_CONTACT_SUCCESS';
//# sourceMappingURL=constants.js.map