"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_SELECT_ORGANIZATION = exports.SELECT_INCIDENT_ORGANIZATION_SUCCESS = exports.SELECT_INCIDENT_ORGANIZATION_REQUEST = exports.SELECT_INCIDENT_ORGANIZATION_FAILURE = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = void 0;
/**
 *
 * SelectOrganizationScreen constants
 *
 */

const GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = 'Home/NewTip/SelectOrganizationScreen/GET_ORGANIZATIONS_REQUEST';
const GET_INTERSECT_ORGANIZATIONS_FAILURE = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = 'Home/NewTip/SelectOrganizationScreen/GET_ORGANIZATIONS_FAILURE';
const GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = 'Home/NewTip/SelectOrganizationScreen/GET_ORGANIZATIONS_SUCCESS';
const TOGGLE_SELECT_ORGANIZATION = exports.TOGGLE_SELECT_ORGANIZATION = 'Home/NewTip/SelectOrganizationScreen/TOGGLE_SELECT_ORGANIZATION';
const SELECT_INCIDENT_ORGANIZATION_REQUEST = exports.SELECT_INCIDENT_ORGANIZATION_REQUEST = 'Home/NewTip/SelectOrganizationScreen/SELECT_INCIDENT_ORGANIZATION_REQUEST';
const SELECT_INCIDENT_ORGANIZATION_FAILURE = exports.SELECT_INCIDENT_ORGANIZATION_FAILURE = 'Home/NewTip/SelectOrganizationScreen/SELECT_INCIDENT_ORGANIZATION_FAILURE';
const SELECT_INCIDENT_ORGANIZATION_SUCCESS = exports.SELECT_INCIDENT_ORGANIZATION_SUCCESS = 'Home/NewTip/SelectOrganizationScreen/SELECT_INCIDENT_ORGANIZATION_SUCCESS';
//# sourceMappingURL=constants.js.map