import Geolocation from 'react-native-geolocation-service';
export declare const LongTimeout = 10000;
export declare const MaximumAge = 300000;
export declare const OptionsForCachedFine: Geolocation.GeoOptions;
export declare const LOCATION_TRACKING_REQUEST = "utils/location/LOCATION_TRACKING_REQUEST";
export declare const LOCATION_TRACKING_FAILURE = "utils/location/LOCATION_TRACKING_FAILURE";
export declare const LOCATION_TRACKING_SUCCESS = "utils/location/LOCATION_TRACKING_SUCCESS";
export declare const GEO_STATUS_REQUEST = "utils/location/GEO_STATUS_REQUEST";
export declare const GEO_STATUS_FAILURE = "utils/location/GEO_STATUS_FAILURE";
export declare const GEO_STATUS_SUCCESS = "utils/location/GEO_STATUS_SUCCESS";
export declare const GET_ALL_GEOFENCS_REQUEST = "utils/location/GET_ALL_GEOFENCS_REQUEST";
export declare const GET_ALL_GEOFENCS_FAILURE = "utils/location/GET_ALL_GEOFENCS_FAILURE";
export declare const GET_ALL_GEOFENCS_SUCCESS = "utils/location/GET_ALL_GEOFENCS_SUCCESS";
export declare const SET_SITE_KEY_LOCATION_REQUEST = "utils/location/SET_SITE_KEY_LOCATION_REQUEST";
export declare const SET_SITE_KEY_LOCATION_FAILURE = "utils/location/SET_SITE_KEY_LOCATION_FAILURE";
export declare const SET_SITE_KEY_LOCATION_SUCCESS = "utils/location/SET_SITE_KEY_LOCATION_SUCCESS";
