/**
 *
 * ContactScreen constants
 *
 */

export const TOGGLE_CONTACT_NOTIFICATION_REQUEST = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_REQUEST';
export const TOGGLE_CONTACT_NOTIFICATION_FAILURE = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_FAILURE';
export const TOGGLE_CONTACT_NOTIFICATION_SUCCESS = 'Home/ContactScreen/TOGGLE_CONTACT_NOTIFICATION_SUCCESS';
export const DELETE_CONTACT_REQUEST = 'Home/ContactScreen/DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_FAILURE = 'Home/ContactScreen/DELETE_CONTACT_FAILURE';
export const DELETE_CONTACT_SUCCESS = 'Home/ContactScreen/DELETE_CONTACT_SUCCESS';
//# sourceMappingURL=constants.js.map