/**
 *
 * NotificationProvider constants
 *
 */

export const SHOW_IOS_FOREGROUND_NOTIFICATION =
  'NotificationProvider/SHOW_IOS_FOREGROUND_NOTIFICATION';
export const HIDE_IOS_FOREGROUND_NOTIFICATION =
  'NotificationProvider/HIDE_IOS_FOREGROUND_NOTIFICATION';
export const ANDROID_HEADLESS_NOTIFICATION_KEY =
  'NotificationProvider/ANDROID_HEADLESS_NOTIFICATION_KEY';
export const NOTIFICATION_BADGES_KEY =
  'NotificationProvider/NOTIFICATION_BADGES_KEY';
export const NOTIFICATION_ESCORT_BADGES_KEY =
  'NotificationProvider/NOTIFICATION_ESCORT_BADGES_KEY';
