"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_PORTRAIT_SUCCESS = exports.UPDATE_PORTRAIT_REQUEST = exports.UPDATE_PORTRAIT_FAILURE = exports.UPDATE_MY_ACCOUNT_NAME_SUCCESS = exports.UPDATE_MY_ACCOUNT_NAME_REQUEST = exports.UPDATE_MY_ACCOUNT_NAME_FAILURE = exports.DELETE_PORTRAIT_SUCCESS = exports.DELETE_PORTRAIT_FAILURE = exports.DELETE_PORTRAIT = exports.CLEAR_MESSAGE_TYPE = void 0;
/**
 *
 * MyAccountScreen constants
 *
 */

const UPDATE_MY_ACCOUNT_NAME_REQUEST = exports.UPDATE_MY_ACCOUNT_NAME_REQUEST = 'Menu/MyAccountScreen/UPDATE_MY_ACCOUNT_NAME_REQUEST';
const UPDATE_MY_ACCOUNT_NAME_FAILURE = exports.UPDATE_MY_ACCOUNT_NAME_FAILURE = 'Menu/MyAccountScreen/UPDATE_MY_ACCOUNT_NAME_FAILURE';
const UPDATE_MY_ACCOUNT_NAME_SUCCESS = exports.UPDATE_MY_ACCOUNT_NAME_SUCCESS = 'Menu/MyAccountScreen/UPDATE_MY_ACCOUNT_NAME_SUCCESS';
const UPDATE_PORTRAIT_REQUEST = exports.UPDATE_PORTRAIT_REQUEST = 'Menu/MyAccountScreen/UPDATE_PORTRAIT_REQUEST';
const UPDATE_PORTRAIT_SUCCESS = exports.UPDATE_PORTRAIT_SUCCESS = 'Menu/MyAccountScreen/UPDATE_PORTRAIT_SUCCESS';
const UPDATE_PORTRAIT_FAILURE = exports.UPDATE_PORTRAIT_FAILURE = 'Menu/MyAccountScreen/UPDATE_PORTRAIT_FAILURE';
const DELETE_PORTRAIT = exports.DELETE_PORTRAIT = 'Menu/MyAccountScreen/DELETE_PORTRAIT';
const DELETE_PORTRAIT_SUCCESS = exports.DELETE_PORTRAIT_SUCCESS = 'Menu/MyAccountScreen/DELETE_PORTRAIT_SUCCESS';
const DELETE_PORTRAIT_FAILURE = exports.DELETE_PORTRAIT_FAILURE = 'Menu/MyAccountScreen/DELETE_PORTRAIT_FAILURE';
const CLEAR_MESSAGE_TYPE = exports.CLEAR_MESSAGE_TYPE = 'Menu/MyAccountScreen/CLEAR_MESSAGE_TYPE';
//# sourceMappingURL=constants.js.map