declare const colors: {
    background: string;
    background2: string;
    background3: string;
    background4: string;
    background5: string;
    gradientColors: string[];
    grey: string;
    grey1: string;
    lightGrey: string;
    highlight: string;
    highlight2: string;
    highlight3: string;
    dark: string;
    darker: string;
    light: string;
    lighter: string;
    nearWhite: string;
    primary: string;
    transparent: string;
    semiTransparent: string;
    white: string;
    black: string;
    red: string;
    darkRed: string;
    green: string;
    blue: string;
    mapOverlay: string[];
    trackThumbOverlay: string[];
    videoCardOverlay: string[];
};
export default colors;
