"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_SELECT_ORGANIZATION = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = void 0;
/**
 *
 * SelectOrganizationScreen constants
 *
 */

const GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = 'Home/Escort/SelectOrganizationScreen/GET_ORGANIZATIONS_REQUEST';
const GET_INTERSECT_ORGANIZATIONS_FAILURE = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = 'Home/Escort/SelectOrganizationScreen/GET_ORGANIZATIONS_FAILURE';
const GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = 'Home/Escort/SelectOrganizationScreen/GET_ORGANIZATIONS_SUCCESS';
const TOGGLE_SELECT_ORGANIZATION = exports.TOGGLE_SELECT_ORGANIZATION = 'Home/Escort/SelectOrganizationScreen/TOGGLE_SELECT_ORGANIZATION';
//# sourceMappingURL=constants.js.map