"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.USER_PHONE_KEY = exports.UPDATE_USER_PORTRAIT = exports.UPDATE_PROFILE_REQUEST = exports.TOKEN_KEY = exports.SET_TIP_CAMERA_VIDEO_INDEX = exports.SET_TIP_CAMERA_MODE = exports.SET_PASSIVE_ESCORT_DATA = exports.SET_LOCATION_ALWAYS_PERMISSION = exports.SET_INCIDENT_ESCORT_DATA = exports.SET_APP_LOCATION = exports.SELECTED_SITEKEY_LOCATION = exports.REMOTE_LOGGER_KEY = exports.LOG_ERROR = exports.LINKS = exports.IS_SHOW_ESCORT_MENU = exports.GET_TWILIO_ACCESS_TOKEN_SUCCESS = exports.GET_TWILIO_ACCESS_TOKEN_REQUEST = exports.GET_TWILIO_ACCESS_TOKEN_FAILURE = exports.GET_PROFILE_SUCCESS = exports.GET_PROFILE_REQUEST = exports.GET_PROFILE_FAILURE = exports.GET_CONFIGS_SUCCESS = exports.GET_CONFIGS_REQUEST = exports.GET_CONFIGS_FAILURE = exports.CLEAR_PASSIVE_ESCORT_DATA = exports.CLEAR_INCIDENT_ESCORT_DATA = exports.CLEAR_APP_LOCATION = void 0;
/**
 *
 * App constants
 *
 */

const TOKEN_KEY = exports.TOKEN_KEY = 'App/TOKEN_KEY';
const USER_PHONE_KEY = exports.USER_PHONE_KEY = 'App/USER_PHONE_KEY';
const REMOTE_LOGGER_KEY = exports.REMOTE_LOGGER_KEY = 'App/REMOTE_LOGGER_KEY';
const GET_CONFIGS_REQUEST = exports.GET_CONFIGS_REQUEST = 'App/GET_CONFIGS_REQUEST';
const GET_CONFIGS_FAILURE = exports.GET_CONFIGS_FAILURE = 'App/GET_CONFIGS_FAILURE';
const GET_CONFIGS_SUCCESS = exports.GET_CONFIGS_SUCCESS = 'App/GET_CONFIGS_SUCCESS';
const GET_PROFILE_REQUEST = exports.GET_PROFILE_REQUEST = 'App/GET_PROFILE_REQUEST';
const GET_PROFILE_FAILURE = exports.GET_PROFILE_FAILURE = 'App/GET_PROFILE_FAILURE';
const GET_PROFILE_SUCCESS = exports.GET_PROFILE_SUCCESS = 'App/GET_PROFILE_SUCCESS';
const UPDATE_PROFILE_REQUEST = exports.UPDATE_PROFILE_REQUEST = 'App/UPDATE_PROFILE_REQUEST';
const SET_TIP_CAMERA_MODE = exports.SET_TIP_CAMERA_MODE = 'App/SET_TIP_CAMERA_MODE';
const SET_TIP_CAMERA_VIDEO_INDEX = exports.SET_TIP_CAMERA_VIDEO_INDEX = 'App/SET_TIP_CAMERA_VIDEO_INDEX';
const GET_TWILIO_ACCESS_TOKEN_REQUEST = exports.GET_TWILIO_ACCESS_TOKEN_REQUEST = 'App/GET_TWILIO_ACCESS_TOKEN_REQUEST';
const GET_TWILIO_ACCESS_TOKEN_FAILURE = exports.GET_TWILIO_ACCESS_TOKEN_FAILURE = 'App/GET_TWILIO_ACCESS_TOKEN_FAILURE';
const GET_TWILIO_ACCESS_TOKEN_SUCCESS = exports.GET_TWILIO_ACCESS_TOKEN_SUCCESS = 'App/GET_TWILIO_ACCESS_TOKEN_SUCCESS';
const LINKS = exports.LINKS = {
  faq: 'https://incidentcode.com/docs/faq.html',
  privacy: 'https://www.incidentco.com/privacy-policy',
  // privacy: 'https://incidentcode.com/docs/privacy.html', // Previou link
  tos: 'https://incidentcode.com/docs/tos.html'
};
const SELECTED_SITEKEY_LOCATION = exports.SELECTED_SITEKEY_LOCATION = 'App/SELECTED_SITEKEY_LOCATION';
const SET_INCIDENT_ESCORT_DATA = exports.SET_INCIDENT_ESCORT_DATA = 'App/SET_INCIDENT_ESCORT_DATA';
const CLEAR_INCIDENT_ESCORT_DATA = exports.CLEAR_INCIDENT_ESCORT_DATA = 'App/CLEAR_INCIDENT_ESCORT_DATA';
const SET_PASSIVE_ESCORT_DATA = exports.SET_PASSIVE_ESCORT_DATA = 'App/SET_PASSIVE_ESCORT_DATA';
const CLEAR_PASSIVE_ESCORT_DATA = exports.CLEAR_PASSIVE_ESCORT_DATA = 'App/CLEAR_PASSIVE_ESCORT_DATA';
const UPDATE_USER_PORTRAIT = exports.UPDATE_USER_PORTRAIT = 'App/UPDATE_USER_PORTRAIT';
const SET_APP_LOCATION = exports.SET_APP_LOCATION = 'App/SET_APP_LOCATION';
const CLEAR_APP_LOCATION = exports.CLEAR_APP_LOCATION = 'App/CLEAR_APP_LOCATION';
const LOG_ERROR = exports.LOG_ERROR = 'App/LOG_ERROR'; // generic log error to db action
const IS_SHOW_ESCORT_MENU = exports.IS_SHOW_ESCORT_MENU = 'App/IS_SHOW_ESCORT_MENU';
const SET_LOCATION_ALWAYS_PERMISSION = exports.SET_LOCATION_ALWAYS_PERMISSION = 'App/SET_LOCATION_ALWAYS_PERMISSION';
//# sourceMappingURL=constants.js.map