"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLE_SELECT_PROCEDURE = exports.TOGGLE_SELECT_ORGANIZATION_GROUP = exports.TOGGLE_SELECT_ORGANIZATION = exports.GET_ORGANIZATION_PROCEDURES_SUCCESS = exports.GET_ORGANIZATION_PROCEDURES_REQUEST = exports.GET_ORGANIZATION_PROCEDURES_FAILURE = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = exports.CLEAR_SELECTIONS = void 0;
/**
 *
 * TimedEscortScreen constants
 *
 */

const GET_INTERSECT_ORGANIZATIONS_REQUEST = exports.GET_INTERSECT_ORGANIZATIONS_REQUEST = 'Home/Escort/TimedEscortScreen/GET_ORGANIZATIONS_REQUEST';
const GET_INTERSECT_ORGANIZATIONS_FAILURE = exports.GET_INTERSECT_ORGANIZATIONS_FAILURE = 'Home/Escort/TimedEscortScreen/GET_ORGANIZATIONS_FAILURE';
const GET_INTERSECT_ORGANIZATIONS_SUCCESS = exports.GET_INTERSECT_ORGANIZATIONS_SUCCESS = 'Home/Escort/TimedEscortScreen/GET_ORGANIZATIONS_SUCCESS';
const GET_ORGANIZATION_PROCEDURES_REQUEST = exports.GET_ORGANIZATION_PROCEDURES_REQUEST = 'Home/Escort/TimedEscortScreen/GET_PROCEDURES_REQUEST';
const GET_ORGANIZATION_PROCEDURES_FAILURE = exports.GET_ORGANIZATION_PROCEDURES_FAILURE = 'Home/Escort/TimedEscortScreen/GET_PROCEDURES_FAILURE';
const GET_ORGANIZATION_PROCEDURES_SUCCESS = exports.GET_ORGANIZATION_PROCEDURES_SUCCESS = 'Home/Escort/TimedEscortScreen/GET_PROCEDURES_SUCCESS';
const TOGGLE_SELECT_ORGANIZATION = exports.TOGGLE_SELECT_ORGANIZATION = 'Home/Escort/TimedEscortScreen/TOGGLE_SELECT_ORGANIZATION';
const TOGGLE_SELECT_ORGANIZATION_GROUP = exports.TOGGLE_SELECT_ORGANIZATION_GROUP = 'Home/Escort/TimedEscortScreen/TOGGLE_SELECT_ORGANIZATION_GROUP';
const TOGGLE_SELECT_PROCEDURE = exports.TOGGLE_SELECT_PROCEDURE = 'Home/Escort/TimedEscortScreen/TOGGLE_SELECT_PROCEDURE';
const CLEAR_SELECTIONS = exports.CLEAR_SELECTIONS = 'Home/Escort/TimedEscortScreen/CLEAR_SELECTIONS';
//# sourceMappingURL=constants.js.map