"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_ORGANIZATIONS_SUCCESS = exports.UPDATE_ORGANIZATIONS_REQUEST = exports.UPDATE_ORGANIZATIONS_FAILURE = exports.TOGGLE_SELECT_ORGANIZATION = exports.GET_ORGANIZATIONS_SUCCESS = exports.GET_ORGANIZATIONS_REQUEST = exports.GET_ORGANIZATIONS_FAILURE = void 0;
/**
 *
 * SelectOrganizationScreen constants
 *
 */

const GET_ORGANIZATIONS_REQUEST = exports.GET_ORGANIZATIONS_REQUEST = 'Onboarding/SelectOrganizationScreen/GET_ORGANIZATIONS_REQUEST';
const GET_ORGANIZATIONS_FAILURE = exports.GET_ORGANIZATIONS_FAILURE = 'Onboarding/SelectOrganizationScreen/GET_ORGANIZATIONS_FAILURE';
const GET_ORGANIZATIONS_SUCCESS = exports.GET_ORGANIZATIONS_SUCCESS = 'Onboarding/SelectOrganizationScreen/GET_ORGANIZATIONS_SUCCESS';
const TOGGLE_SELECT_ORGANIZATION = exports.TOGGLE_SELECT_ORGANIZATION = 'Onboarding/SelectOrganizationScreen/TOGGLE_SELECT_ORGANIZATION';
const UPDATE_ORGANIZATIONS_REQUEST = exports.UPDATE_ORGANIZATIONS_REQUEST = 'Onboarding/SelectOrganizationScreen/UPDATE_ORGANIZATIONS_REQUEST';
const UPDATE_ORGANIZATIONS_FAILURE = exports.UPDATE_ORGANIZATIONS_FAILURE = 'Onboarding/SelectOrganizationScreen/UPDATE_ORGANIZATIONS_FAILURE';
const UPDATE_ORGANIZATIONS_SUCCESS = exports.UPDATE_ORGANIZATIONS_SUCCESS = 'Onboarding/SelectOrganizationScreen/UPDATE_ORGANIZATIONS_SUCCESS';
//# sourceMappingURL=constants.js.map