"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SHOW_IOS_FOREGROUND_NOTIFICATION = exports.NOTIFICATION_ESCORT_BADGES_KEY = exports.NOTIFICATION_BADGES_KEY = exports.HIDE_IOS_FOREGROUND_NOTIFICATION = exports.ANDROID_HEADLESS_NOTIFICATION_KEY = void 0;
/**
 *
 * NotificationProvider constants
 *
 */

const SHOW_IOS_FOREGROUND_NOTIFICATION = exports.SHOW_IOS_FOREGROUND_NOTIFICATION = 'NotificationProvider/SHOW_IOS_FOREGROUND_NOTIFICATION';
const HIDE_IOS_FOREGROUND_NOTIFICATION = exports.HIDE_IOS_FOREGROUND_NOTIFICATION = 'NotificationProvider/HIDE_IOS_FOREGROUND_NOTIFICATION';
const ANDROID_HEADLESS_NOTIFICATION_KEY = exports.ANDROID_HEADLESS_NOTIFICATION_KEY = 'NotificationProvider/ANDROID_HEADLESS_NOTIFICATION_KEY';
const NOTIFICATION_BADGES_KEY = exports.NOTIFICATION_BADGES_KEY = 'NotificationProvider/NOTIFICATION_BADGES_KEY';
const NOTIFICATION_ESCORT_BADGES_KEY = exports.NOTIFICATION_ESCORT_BADGES_KEY = 'NotificationProvider/NOTIFICATION_ESCORT_BADGES_KEY';
//# sourceMappingURL=constants.js.map