"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TRIGGER_COUNTDOWN_WARNING = exports.START_VIRTUAL_ESCORT_SUCCESS = exports.START_VIRTUAL_ESCORT_REQUEST = exports.START_VIRTUAL_ESCORT_FAILURE = exports.START_PASSIVE_ESCORT_SUCCESS = exports.START_PASSIVE_ESCORT_REQUEST = exports.START_PASSIVE_ESCORT_FAILURE = exports.SHOW_SET_TIMER_MODAL = exports.SHOW_SAFE_MODAL = exports.SHOW_PANIC_INFO = exports.SHOW_EXIT_PANIC_MODAL = exports.SHOW_CALL_MODAL = exports.SET_TIMER_VALUE_SUCCESS = exports.SET_TIMER_VALUE_REQUEST = exports.SET_TIMER_VALUE_FAILURE = exports.SET_SAFETY_TIMER = exports.LOG_ESCORT_ACTION_REQUEST = exports.LOG_ESCORT_ACTION_FAILURE = exports.IM_SAFE_SUCCESS = exports.IM_SAFE_REQUEST = exports.IM_SAFE_FAILURE = exports.HIDE_SET_TIMER_MODAL = exports.HIDE_SAFE_MODAL = exports.HIDE_PANIC_INFO = exports.HIDE_EXIT_PANIC_MODAL = exports.HIDE_CALL_MODAL = exports.GET_PROCEDURE_SUCCESS = exports.GET_PROCEDURE_REQUEST = exports.GET_PROCEDURE_FAILURE = exports.ENTER_PANIC_MODE_SUCCESS = exports.ENTER_PANIC_MODE_FAILURE = exports.ENTER_PANIC_MODE = exports.COMPLETE_PROCEDURE_ACTION = exports.CLEAR_PROCEDURE = exports.CLEAR_ESCORT_ERROR = exports.CLEAR_ARE_YOU_SAFE = exports.CANCEL_COUNTDOWN_WARNING = void 0;
/**
 *
 * CountdownScreen constants
 *
 */

const GET_PROCEDURE_REQUEST = exports.GET_PROCEDURE_REQUEST = 'Home/Escort/CountdownScreen/GET_PROCEDURE_REQUEST';
const GET_PROCEDURE_SUCCESS = exports.GET_PROCEDURE_SUCCESS = 'Home/Escort/CountdownScreen/GET_PROCEDURE_SUCCESS';
const GET_PROCEDURE_FAILURE = exports.GET_PROCEDURE_FAILURE = 'Home/Escort/CountdownScreen/GET_PROCEDURE_FAILURE';
const SHOW_SET_TIMER_MODAL = exports.SHOW_SET_TIMER_MODAL = 'Home/Escort/CountdownScreen/SHOW_SET_TIMER_MODAL';
const HIDE_SET_TIMER_MODAL = exports.HIDE_SET_TIMER_MODAL = 'Home/Escort/CountdownScreen/HIDE_SET_TIMER_MODAL';
const SET_TIMER_VALUE_REQUEST = exports.SET_TIMER_VALUE_REQUEST = 'Home/Escort/CountdownScreen/SET_TIMER_VALUE_REQUEST';
const SET_TIMER_VALUE_SUCCESS = exports.SET_TIMER_VALUE_SUCCESS = 'Home/Escort/CountdownScreen/SET_TIMER_VALUE_SUCCESS';
const SET_TIMER_VALUE_FAILURE = exports.SET_TIMER_VALUE_FAILURE = 'Home/Escort/CountdownScreen/SET_TIMER_VALUE_FAILURE';
const COMPLETE_PROCEDURE_ACTION = exports.COMPLETE_PROCEDURE_ACTION = 'Home/Escort/CountdownScreen/COMPLETE_PROCEDURE_ACTION';
const SHOW_CALL_MODAL = exports.SHOW_CALL_MODAL = 'Home/Escort/CountdownScreen/SHOW_CALL_MODAL';
const HIDE_CALL_MODAL = exports.HIDE_CALL_MODAL = 'Home/Escort/CountdownScreen/HIDE_CALL_MODAL';
const SHOW_SAFE_MODAL = exports.SHOW_SAFE_MODAL = 'Home/Escort/CountdownScreen/SHOW_SAFE_MODAL';
const HIDE_SAFE_MODAL = exports.HIDE_SAFE_MODAL = 'Home/Escort/CountdownScreen/HIDE_SAFE_MODAL';
const SHOW_PANIC_INFO = exports.SHOW_PANIC_INFO = 'Home/Escort/CountdownScreen/SHOW_PANIC_INFO';
const HIDE_PANIC_INFO = exports.HIDE_PANIC_INFO = 'Home/Escort/CountdownScreen/HIDE_PANIC_INFO';
const ENTER_PANIC_MODE = exports.ENTER_PANIC_MODE = 'Home/Escort/CountdownScreen/ENTER_PANIC_MODE';
const ENTER_PANIC_MODE_SUCCESS = exports.ENTER_PANIC_MODE_SUCCESS = 'Home/Escort/CountdownScreen/ENTER_PANIC_MODE_SUCCESS';
const ENTER_PANIC_MODE_FAILURE = exports.ENTER_PANIC_MODE_FAILURE = 'Home/Escort/CountdownScreen/ENTER_PANIC_MODE_FAILURE';
const SHOW_EXIT_PANIC_MODAL = exports.SHOW_EXIT_PANIC_MODAL = 'Home/Escort/CountdownScreen/SHOW_EXIT_PANIC_MODAL';
const HIDE_EXIT_PANIC_MODAL = exports.HIDE_EXIT_PANIC_MODAL = 'Home/Escort/CountdownScreen/HIDE_EXIT_PANIC_MODAL';
const IM_SAFE_REQUEST = exports.IM_SAFE_REQUEST = 'Home/Escort/CountdownScreen/IM_SAFE_REQUEST';
const IM_SAFE_FAILURE = exports.IM_SAFE_FAILURE = 'Home/Escort/CountdownScreen/IM_SAFE_FAILURE';
const IM_SAFE_SUCCESS = exports.IM_SAFE_SUCCESS = 'Home/Escort/CountdownScreen/IM_SAFE_SUCCESS';
const TRIGGER_COUNTDOWN_WARNING = exports.TRIGGER_COUNTDOWN_WARNING = 'Home/Escort/CountdownScreen/TRIGGER_COUNTDOWN_WARNING';
const CANCEL_COUNTDOWN_WARNING = exports.CANCEL_COUNTDOWN_WARNING = 'Home/Escort/CountdownScreen/CANCEL_COUNTDOWN_WARNING';
const START_PASSIVE_ESCORT_REQUEST = exports.START_PASSIVE_ESCORT_REQUEST = 'Home/Escort/CountdownScreen/START_PASSIVE_ESCORT_REQUEST';
const START_PASSIVE_ESCORT_SUCCESS = exports.START_PASSIVE_ESCORT_SUCCESS = 'Home/Escort/CountdownScreen/START_PASSIVE_ESCORT_SUCCESS';
const START_PASSIVE_ESCORT_FAILURE = exports.START_PASSIVE_ESCORT_FAILURE = 'Home/Escort/CountdownScreen/START_PASSIVE_ESCORT_FAILURE';
const START_VIRTUAL_ESCORT_REQUEST = exports.START_VIRTUAL_ESCORT_REQUEST = 'Home/Escort/CountdownScreen/START_VIRTUAL_ESCORT_REQUEST';
const START_VIRTUAL_ESCORT_SUCCESS = exports.START_VIRTUAL_ESCORT_SUCCESS = 'Home/Escort/CountdownScreen/START_VIRTUAL_ESCORT_SUCCESS';
const START_VIRTUAL_ESCORT_FAILURE = exports.START_VIRTUAL_ESCORT_FAILURE = 'Home/Escort/CountdownScreen/START_VIRTUAL_ESCORT_FAILURE';
const CLEAR_ARE_YOU_SAFE = exports.CLEAR_ARE_YOU_SAFE = 'Home/Escort/CountdownScreen/CLEAR_ARE_YOU_SAFE';
const LOG_ESCORT_ACTION_REQUEST = exports.LOG_ESCORT_ACTION_REQUEST = 'Home/Escort/CountdownScreen/LOG_ESCORT_ACTION_REQUEST';
const LOG_ESCORT_ACTION_FAILURE = exports.LOG_ESCORT_ACTION_FAILURE = 'Home/Escort/CountdownScreen/LOG_ESCORT_ACTION_FAILURE';
const CLEAR_ESCORT_ERROR = exports.CLEAR_ESCORT_ERROR = 'Home/Escort/CountdownScreen/CLEAR_ESCORT_ERROR';
const CLEAR_PROCEDURE = exports.CLEAR_PROCEDURE = 'Home/Escort/CountdownScreen/CLEAR_PROCEDURE';
const SET_SAFETY_TIMER = exports.SET_SAFETY_TIMER = 'Home/Escort/CountdownScreen/SET_SAFETY_TIMER';
//# sourceMappingURL=constants.js.map